kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/devwebapp/config"
type: Opaque
stringData:
  username: <username>
  password: <password>
